FROM node:8

# Development packages
RUN apt-get update;

# Create app directory
WORKDIR /usr/src/api

# Install app dependencies
COPY package.json .
COPY package.json package-lock.json ./

RUN npm install

# Bundle app source
COPY . .

EXPOSE 3030
CMD ["npm", "run", "start"]
