FROM node:latest

# Development packages
RUN apt-get update;

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json .
COPY package.json package-lock.json ./

ENV MONGO_URL=

RUN npm install

# Bundle app source
COPY . .

EXPOSE 3030
CMD [ "npm", "start"]
