version: '3'
services:
  mm-mongo:
     image: mongo
     volumes:
       - /tmp/micronetsMongo:/data/db
     command: mongod --port 27018
     ports:
       - "27018:27018"
  mm-api:
    build:
      context: ./../..
      dockerfile: docker/dev/Dockerfile.api
    image: micronets-manager-api-dev
    environment:
      - NODE_ENV=development
      - PORT=3030
      - NETWORK_MODE=false
      - MONGO_URL=mongodb://mongo:27018/micronets
    depends_on:
      - mm-mongo
    ports:
      - '3030:3030'

  mm-app:
    build:
      context: ./../..
      dockerfile: docker/dev/Dockerfile.app
    image: micronets-manager-client-dev
    environment:
      - NODE_ENV=development
      - PORT=8080
      - NETWORK_MODE=false
      - MONGO_URL=mongodb://mongo:27018/micronets
    depends_on:
      - mm-mongo
      - mm-api
    ports:
      - '8080:8080'

