FROM node:latest

# Development packages
RUN apt-get update;

# Create api directory
WORKDIR /usr/src/micronets-manager

# Bundle api source
COPY . .
RUN ls -a

ENV MONGO_URL=
RUN npm install

EXPOSE 3030
CMD [ "npm", "run", "start"]