FROM node:latest

WORKDIR /usr/src/app

# Install app dependencies
COPY app/package.json .
COPY app/package.json app/package-lock.json ./

ENV MONGO_URL=
ENV REDIS_URL=

RUN npm install

# Bundle app source
COPY app .

EXPOSE 3000

CMD ["node", "services/"]