version: '3'

volumes:
  mongodb:

services:

  mongodb:
       image: mongo
       volumes:
         - mongodb:/data/db

  api:
    build:
      context: .
    environment:
      - NODE_ENV=production
      - PORT=3030
      - NETWORK_MODE=false
      - MM_MONGO_DB_URL=mongodb://mongodb/micronets
    env_file:
      - api-config-vars.env

    depends_on:
      - mongodb

  app:
    build:
      context: app
    environment:
      - NODE_ENV=production
      - PORT=8080
      - MM_SERVER_BASE_URL=http://api:3030
      - MSO_PORTAL_BASE_URL=${MM_MSO_PORTAL_BASE_URL}
      - SUBSCRIBER_ID=${MM_SUBSCRIBER_ID}
      - TEST_ID=${MM_SUBSCRIBER_ID}
    depends_on:
      - api
