version: '3'
services:
  micronets-manager:
    image: community.cablelabs.com:4567/micronets-docker/micronets-manager
    ports:
      - "3030:3030"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
