version: '3'
services:
  mongo:
     image: mongo
     volumes:
       - /tmp/mongodb:/data/db
     network_mode: "host"
     ports:
       - "27017:27017"
  api:
    build:
      context: ./
      dockerfile: docker/dev/Dockerfile.api
    image: community.cablelabs.com:4567/micronets-docker/micronets-manager-api:latest
    network_mode: "host"
    environment:
      - NODE_ENV=production
      - PORT=3030
      - NETWORK_MODE=true
      - MONGO_URL=mongodb://127.0.0.1:27017/micronets
    depends_on:
      - mongo
    ports:
      - '3030:3030'

  app:
    build:
      context: ./
      dockerfile: docker/dev/Dockerfile.app
    image: community.cablelabs.com:4567/micronets-docker/micronets-manager-client:latest
    network_mode: "host"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - NETWORK_MODE=true
      - MONGO_URL=mongodb://127.0.0.1:27017/micronets
    depends_on:
      - mongo
      - api
    ports:
      - '8080:8080'

