version: '3'

volumes:
  mongodb:

services:

  mongodb:
       image: mongo
       volumes:
         - mongodb:/data/db

  api:
    image: micronets-manager_api
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - MM_API_LISTEN_HOST=0.0.0.0
      - MM_API_LISTEN_PORT=3030
      - MM_MONGO_DB_URL=mongodb://mongodb/micronets
    env_file:
      - mm-config-env

  app:
    image: micronets-manager_app
    depends_on:
      - api
    environment:
      - NODE_ENV=production
      - MM_SERVER_BASE_URL=http://api:3030

      - MM_APP_LISTEN_HOST=0.0.0.0
      - MM_APP_LISTEN_PORT=8080
      - MM_SERVER_BASE_URL=http://api:3030
      - TEST_ID=${MM_SUBSCRIBER_ID}
    env_file:
      - mm-app-config.env
