version: '3'
services:
  mongo:
       image: mongo
       volumes:
         - /tmp/mongodb:/data/db
       network_mode: "host"
       ports:
         - "27017:27017"
  api:
    build:
      context: ./../..
      dockerfile: docker/dev/Dockerfile.api
    image: micronets-manager-api-dev
    network_mode: "host"
    environment:
      - NODE_ENV=production
      - PORT=3030
      - MONGO_URL=mongodb://127.0.0.1:27017/micronets
    depends_on:
      - mongo
    volumes:
      - ./../../api:/usr/src/api
    ports:
      - '3030:3030'


  app:
    build:
      context: ./../..
      dockerfile: docker/dev/Dockerfile.app
    image: micronets-manager-client-dev
    network_mode: "host"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - MONGO_URL=mongodb://127.0.0.1:27017/micronets
    depends_on:
      - mongo
      - api
    volumes:
      - ./../../app:/usr/src/app
    ports:
      - '8080:8080'
