version: '3'
services:
  mongo:
       image: mongo
       volumes:
         - /tmp/mongodb:/data/db
       ports:
         - "27017:27017"
  api:
    build:
      context: ./../..
      dockerfile: docker/dev/Dockerfile.api
    image: micronets-manager-api-dev
    environment:
      - NODE_ENV=production
      - PORT=3030
      - MONGO_URL=mongodb://mongo:27017/micronets
    network: host
    links:
      - mongo
    volumes:
      - ./../../api:/usr/src/api
    ports:
      - '3030:3030'

  app:
    build:
      context: ./../..
      dockerfile: docker/dev/Dockerfile.app
    image: micronets-manager-client-dev
    environment:
      - NODE_ENV=production
      - PORT=8080
      - MONGO_URL=mongodb://mongo:27017/micronets
    network: host
    links:
      - mongo
      - api
    volumes:
      - ./../../app:/usr/src/app
    ports:
      - '8080:8080'

#  mongo:
#     image: mongo
#     volumes:
#       - /data/mongodb/db:/data/db
#     ports:
#       - "27017:27017"



