#version: "3"
#services:
#  app:
#    image: code.cablelabs.com:4567/micronets/micronets-manager-app
#    ports:
#      - "3000:3000"
#    depends_on:
#      - mongo
#      - redis
#  mongo:
#    image: mongo
#    ports:
#      - "27017:27017"
#
#  redis:
#      image: redis:4.0.5-alpine
#      entrypoint: redis-server --appendonly yes
#      hostname: redis
#      restart: always
#      ports:
#             - "6379:6379"
