#FROM node:8
#
## Development packages
#RUN apt-get update;
#
## Create app directory
#WORKDIR /usr/src/app
#
## Install app dependencies
#COPY package.json .
#COPY package.json package-lock.json ./
#
#RUN npm install
#
## Bundle app source
#COPY . .
#
#EXPOSE 3000
#EXPOSE 8080
#CMD [ "npm", "server", "client" ]
#
#FROM node:8
#
## Development packages
#RUN apt-get update;
#
## Create app directory
#WORKDIR /usr/src/app
#
## Install app dependencies
#COPY package.json .
#COPY package.json package-lock.json ./
#
#RUN npm install
#
## Bundle app source
#COPY . .
#
#EXPOSE 3000
#CMD ["npm", "run", "server"]
