version: '2.4'

networks:
  mm-priv-network:
    labels:
      com.cablelabs.micronets.resource-type: mm-priv-network
      com.cablelabs.micronets.subscriber-id: ${MM_SUBSCRIBER_ID}

volumes:
  mongodb:
    labels:
      com.cablelabs.micronets.resource-type: mm-mongo-vol
      com.cablelabs.micronets.subscriber-id: ${MM_SUBSCRIBER_ID}

services:
  mongodb:
    image: mongo
    mem_limit: 200m
    # restart: on-failure
    volumes:
      - mongodb:/data/db
    networks:
      - mm-priv-network
    labels:
      com.cablelabs.micronets.resource-type: mm-mongo
      com.cablelabs.micronets.subscriber-id: ${MM_SUBSCRIBER_ID}
  api:
    image: "${MM_API_SOURCE_IMAGE}"
    depends_on:
      - mongodb
    mem_limit: 200m
    # restart: on-failure
    volumes:
      - ${MM_CERTS_DIR}:/usr/src/micronets-manager/certs:ro
    networks:
      - mm-priv-network
    command: ["node", "--inspect=0.0.0.0:9229", "api/"]
    environment:
      NODE_ENV: production
      MM_API_LISTEN_HOST: 0.0.0.0
      MM_API_LISTEN_PORT: 3030
      MM_MONGO_DB_URL: mongodb://mongodb/micronets
      MM_SUBSCRIBER_ID: ${MM_SUBSCRIBER_ID}
      MM_API_PUBLIC_BASE_URL: https://dev.mm-api.micronets.in/sub/${MM_SUBSCRIBER_ID}/api
      MM_APP_PUBLIC_BASE_URL: https://dev.mm-api.micronets.in/sub/${MM_SUBSCRIBER_ID}/app
      MM_IDENTITY_SERVER_BASE_URL: http://dev.mud-manager-api.micronets.in:8888/
      MM_MSO_PORTAL_BASE_URL: https://dev.mso-portal-api.micronets.in
      MM_MSO_PORTAL_AUTH_SECRET: ${MM_MSO_SECRET}
      MM_MUD_MANAGER_BASE_URL: http://dev.mud-manager-api.micronets.in:8888
      MM_MUD_REGISTRY_BASE_URL: https://registry.micronets.in/mud/v1
      MM_GATEWAY_WEBSOCKET_BASE_URL: wss://ws-proxy-api.micronets.in:5050/micronets/v1/ws-proxy/gw
    labels:
      com.cablelabs.micronets.resource-type: mm-api
      com.cablelabs.micronets.subscriber-id: ${MM_SUBSCRIBER_ID}

#  app:
#    image: "${MM_APP_SOURCE_IMAGE}"
#    depends_on:
#      - api
#    mem_limit: 200m
#    # restart: on-failure
#    networks:
#      - mm-priv-network
#    environment:
#      - NODE_ENV=production
#      - MM_SERVER_BASE_URL=http://api:3030
#      - MM_APP_LISTEN_HOST=0.0.0.0
#      - MM_APP_LISTEN_PORT=8080
#      - MM_SERVER_BASE_URL=http://api:3030
#      - TEST_ID=${MM_SUBSCRIBER_ID}
#    env_file:
#      - "${MM_API_ENV_FILE}"
#    labels:
#      - com.cablelabs.micronets.containertype: micronets-manager-api

