version: '2.4'

networks:
  mm-priv-network:
    labels:
      com.cablelabs.micronets.resource-type: mm-priv-network
      com.cablelabs.micronets.subscriber-id: ${MM_SUBSCRIBER_ID}

volumes:
  mongodb:
    labels:
      com.cablelabs.micronets.resource-type: mm-mongo-vol
      com.cablelabs.micronets.subscriber-id: ${MM_SUBSCRIBER_ID}

services:
  mongodb:
    image: mongo
    mem_limit: 200m
    # restart: on-failure
    volumes:
      - mongodb:/data/db
    networks:
      - mm-priv-network
    labels:
      com.cablelabs.micronets.resource-type: mm-mongo
      com.cablelabs.micronets.subscriber-id: ${MM_SUBSCRIBER_ID}
  api:
    image: "${MM_API_SOURCE_IMAGE}"
    depends_on:
      - mongodb
    mem_limit: 200m
    # restart: on-failure
    networks:
      - mm-priv-network
    environment:
      NODE_ENV: production
      MM_API_LISTEN_HOST: 0.0.0.0
      MM_API_LISTEN_PORT: 3030
      MM_MONGO_DB_URL: mongodb://mongodb/micronets
      MM_SUBSCRIBER_ID: ${MM_SUBSCRIBER_ID}
      MM_API_PUBLIC_BASE_URL: https://dev.mm-api.micronets.in/sub/${MM_SUBSCRIBER_ID}/api
      MM_APP_PUBLIC_BASE_URL: https://dev.mm-api.micronets.in/sub/${MM_SUBSCRIBER_ID}/app
      MM_IDENTITY_SERVER_BASE_URL: http://dev.mud-manager-api.micronets.in:8888/
      MM_MSO_PORTAL_BASE_URL: https://dev.mso-portal-api.micronets.in
      MM_MSO_PORTAL_AUTH_SECRET: c19ee1c7e25ad6166a8ab0ef6d91c9f05c331ba6ab4d16abb7672cb4835dad70fe45f9d28664c88bd31131282c32917479faf7043882c70e8707f9b6d42948bc4f69afc46dea21fc486f369919dd2b1c97cbd30b19d858c87a8f7614c56cf4ffd8eec057785c859db09ff0a236135d400f0c8b256a5fdf23ef183fb16c0db3d12030c9a4c977f927aeeb4afd2e9d10ec07041f080db3e010a79e64ae3f997d95a6ad3896b0d736f59ff71dc1474e045df19e6f42210c5d2c1ecd9c4e0081b095c1c0b6d40ac8e44dc68f494c8c172897ebdbf9cb46974264734eef39e3c4ecf0fbf22fef5f3c7c06ba60e3b3413527a24114bb7ada20bc781590e3799c0c1aa9
      MM_MUD_MANAGER_BASE_URL: http://dev.mud-manager-api.micronets.in:8888
      MM_MUD_REGISTRY_BASE_URL: https://registry.micronets.in/mud/v1
      MM_GATEWAY_WEBSOCKET_BASE_URL: wss://ws-proxy-api.micronets.in:5050/micronets/v1/ws-proxy/gw
    labels:
      com.cablelabs.micronets.resource-type: mm-api
      com.cablelabs.micronets.subscriber-id: ${MM_SUBSCRIBER_ID}

#  app:
#    image: "${MM_APP_SOURCE_IMAGE}"
#    depends_on:
#      - api
#    mem_limit: 200m
#    # restart: on-failure
#    networks:
#      - mm-priv-network
#    environment:
#      - NODE_ENV=production
#      - MM_SERVER_BASE_URL=http://api:3030
#      - MM_APP_LISTEN_HOST=0.0.0.0
#      - MM_APP_LISTEN_PORT=8080
#      - MM_SERVER_BASE_URL=http://api:3030
#      - TEST_ID=${MM_SUBSCRIBER_ID}
#    env_file:
#      - "${MM_API_ENV_FILE}"
#    labels:
#      - com.cablelabs.micronets.containertype: micronets-manager-api

